# Generated by Django 4.1.6 on 2023-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=7)),
                ('category', models.CharField(blank=True, max_length=12, null=True)),
                ('abilities', models.CharField(blank=True, max_length=12, null=True)),
                ('pokemon_type', models.CharField(blank=True, max_length=12, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
