# Generated by Django 4.1.6 on 2023-02-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemonability_pokemons_pokemon_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemons',
            name='pokemon_evolution',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
